import snapshot from '../../../data/nairobi-exposure.json'

// Generated by client/scripts/build-nairobi-snapshot.py from the supplied CSV.
// Every location and insured value in this file is synthetic.
export type ExposureRow = [
  id: string,
  latitude: number,
  longitude: number,
  classIndex: number,
  tivKes: number,
  common: number,
  occasional: number,
  moderate: number,
  severe: number,
  extreme: number,
]

export const exposureRows = snapshot as unknown as ExposureRow[]

export const constructionClasses = [
  { key: 'informal_iron_sheet', label: 'Informal iron sheet', damageCap: 0.75, color: '#67e8f9' },
  { key: 'semi_permanent', label: 'Semi-permanent', damageCap: 0.60, color: '#a7f3d0' },
  { key: 'permanent_masonry', label: 'Permanent masonry', damageCap: 0.45, color: '#fcd34d' },
  { key: 'concrete_rcc', label: 'Concrete / RCC', damageCap: 0.30, color: '#c4b5fd' },
] as const

// The source tiers are susceptibility masks, not measured depth or return periods.
// This provisional mapping follows the starter guide: the widest mask is the rarest event.
export const scenarios = [
  { key: 'rp5', label: '1-in-5', returnPeriod: 5, tier: 'extreme', scoreIndex: 9 },
  { key: 'rp10', label: '1-in-10', returnPeriod: 10, tier: 'severe', scoreIndex: 8 },
  { key: 'rp20', label: '1-in-20', returnPeriod: 20, tier: 'moderate', scoreIndex: 7 },
  { key: 'rp50', label: '1-in-50', returnPeriod: 50, tier: 'occasional', scoreIndex: 6 },
  { key: 'rp100', label: '1-in-100', returnPeriod: 100, tier: 'common', scoreIndex: 5 },
] as const

export type Scenario = (typeof scenarios)[number]
export type ScenarioKey = Scenario['key']

export function formatKes(value: number, digits = 1) {
  if (value >= 1_000_000_000) return `KSh ${(value / 1_000_000_000).toFixed(digits)}B`
  if (value >= 1_000_000) return `KSh ${(value / 1_000_000).toFixed(digits)}M`
  return `KSh ${Math.round(value).toLocaleString('en-KE')}`
}

export function scoreFor(row: ExposureRow, scenario: Scenario) {
  return row[scenario.scoreIndex]
}

export function damageRatioFor(row: ExposureRow, scenario: Scenario) {
  const score = scoreFor(row, scenario)
  // Provisional proxy-to-damage conversion; these caps are demo assumptions.
  return constructionClasses[row[3]].damageCap * Math.pow(score, 1.2)
}

export function lossFor(row: ExposureRow, scenario: Scenario) {
  return row[4] * damageRatioFor(row, scenario)
}

function summarize(scenario: Scenario) {
  const classLosses = constructionClasses.map(() => 0)
  const classExposure = constructionClasses.map(() => 0)
  const classAffected = constructionClasses.map(() => 0)
  let lossKes = 0
  let affectedCount = 0
  let affectedTivKes = 0

  for (const row of exposureRows) {
    const classIndex = row[3]
    const loss = lossFor(row, scenario)
    classExposure[classIndex] += row[4]
    classLosses[classIndex] += loss
    lossKes += loss
    if (scoreFor(row, scenario) > 0) {
      affectedCount += 1
      classAffected[classIndex] += 1
      affectedTivKes += row[4]
    }
  }

  return { scenario, lossKes, affectedCount, affectedTivKes, classLosses, classExposure, classAffected }
}

export const totalExposureKes = exposureRows.reduce((sum, row) => sum + row[4], 0)
export const scenarioSummaries = Object.fromEntries(scenarios.map((scenario) => [scenario.key, summarize(scenario)])) as Record<ScenarioKey, ReturnType<typeof summarize>>
export type ScenarioSummary = (typeof scenarioSummaries)[ScenarioKey]

export const epCurve = scenarios.map((scenario) => ({
  returnPeriod: scenario.returnPeriod,
  probability: 1 / scenario.returnPeriod,
  lossKes: scenarioSummaries[scenario.key].lossKes,
  affectedCount: scenarioSummaries[scenario.key].affectedCount,
}))
